<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXqyFxYS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXqyFxYS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXqyFxYS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXqyFxYS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXqyFxYS\App_KernelDevDebugContainer([
    'container.build_hash' => 'XqyFxYS',
    'container.build_id' => '2c6bd5be',
    'container.build_time' => 1671389384,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXqyFxYS');
